name: Test module

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      testserver:
        # Docker Hub image
        image: krpc/testserver:0.4.8
        options: --type=websocket
        ports:
          - 50000:50000
          - 50001:50001

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm build
    - run: until curl localhost:50000; do sleep 1; done
    - run: npm test
